theme : "hyde-hyde"
baseurl: 'https://halilkeklik.com/'
title: Halil Keklik
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
footnoteReturnLinkContents: ^
googleAnalytics: UA-XXXXXXXX-XX
disqusShortName: yourdisqusshortname
permalinks:
  posts : "/:year/:month/:day/:filename/"
  page : "/:filename/"
params:
  author: "HalilKeklik"
  title: "HalilKeklik"

  goatcounter:
    domain: stats.domain.com
  
  mainSections : ["posts"]
  favicon : "favicon.ico"

  social:
    github: <halilkeklik>
    linkedin: <halil-keklik-594b21179>
menu:
  main:
    - name: Posts
      weight: 100
      identifier: posts
      url: /posts/
    - name: About
      identifier: about
      weight: 300
      url: /about/
outputs:
  section:
    - JSON
    - HTML


